services:
  next-app:
    build: 
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - 3000:3000
  express-app:
    build: 
      context: ./backend
      dockerfile: DockerFile
    ports:
      - 3001:3001